In [26]:
import pyaudio
import numpy as np
import keyboard

class Tone:
    def __init__(self, volume=.5, rate=48000, channels=1): 
        self.volume = volume  
        self.rate = rate
        self.channels = channels
        self.p=pyaudio.PyAudio()
        self.stream = self.p.open(format=pyaudio.paFloat32,
                                  channels=self.channels, rate=self.rate, output=True)

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        self.stop() 

    def stop(self): 
        self.stream.stop_stream()
        self.stream.close()
        self.p.terminate()

    def play(self, octave, note, duration):
        f = 2**(octave) * 55 * 2**(((note) - 10)/12) 
        sample = (np.sin(2* np.pi* np.arange(self.rate * duration) * f / self.rate)).astype(np.float32)
        self.stream.write(self.volume * sample)

with Tone() as tone:
#     for n in [1, 3, 5, 6, 8, 10, 12, 13]:
#         tone.play(3, n, 4)

    while True:
        num = input("정수 입력(1, 3, 5, 6, 8, 10, 12, 13)")
        print(f"입력된 정수 값 {num}")
        if num=='1':
            tone.play(3, 1, 4)
        elif num=='3':
            tone.play(3, 3, 4)
        elif num=='5':
            tone.play(3, 5, 4)
        elif num=='6':
            tone.play(3, 6, 4)
        else:
            print("없는 값")
            break


정수 입력(1, 3, 5, 6, 8, 10, 12, 13) 1


입력된 정수 값 1


정수 입력(1, 3, 5, 6, 8, 10, 12, 13) 3


입력된 정수 값 3


정수 입력(1, 3, 5, 6, 8, 10, 12, 13) 5


입력된 정수 값 5


정수 입력(1, 3, 5, 6, 8, 10, 12, 13) 6


입력된 정수 값 6


정수 입력(1, 3, 5, 6, 8, 10, 12, 13) 8


입력된 정수 값 8
없는 값


In [35]:
import numpy as np
from pop import Cds, delay, Pilot

cds = Cds(7)    # 빛의 세기를 감지 빛감지센서
Car = Pilot.AutoCar()

# for i in range(10):
#     value = cds.readAverage()
#     print(value)
#     delay(500)

for i in range(50):
    value = cds.readAverage()
    #print(value)
    if value >= 500:
        #Car.setSpeed(value/16)
        Car.backward(value/10)
        #print(value)
    elif value <= 46:
        Car.stop()
        

In [36]:
from pop import Pilot
Car = Pilot.AutoCar()
Car.stop()

In [37]:
import pandas as pd

arr =  [1, 2, 3, 4]
type(arr)

list

In [39]:
s = pd.Series(arr)  # series 타입 객체 변환
print(s)  # index와 value 형태로 변환된다 (왼쪽은 0번지 오른쪽은 값) 
type(s)

0    1
1    2
2    3
3    4
dtype: int64


pandas.core.series.Series

In [55]:
import pandas as pd

value = [32, 68, 220, 77]
index = ["온도", "습도", "강수량", "불쾌지수"]

sr = pd.Series(value, index)
print(sr.index)
print(sr.values)

Index(['온도', '습도', '강수량', '불쾌지수'], dtype='object')
[ 32  68 220  77]


In [52]:
print(type(sr))
print(sr)
print(sr["온도"])   # 인덱스를 통한 접근

<class 'pandas.core.series.Series'>
온도       32
습도       68
강수량     220
불쾌지수     77
좋음        0
dtype: int64
32


In [53]:
print(sr.iloc[0])   # iloc 행번호로 출력 
print(sr.loc['습도'])   # loc 인덱스를 통해 출력 
print(sr.iloc[-1])

32
68
0


In [57]:
sr.loc['좋음'] = 0
print(sr)

온도       32
습도       68
강수량     220
불쾌지수     77
좋음        0
dtype: int64


In [59]:
sr2 = sr.drop('좋음')
print(sr)   # series 의 원본에는 삭제가 되지 않았다
print(sr2)  # 삭제된 새로운 series

온도       32
습도       68
강수량     220
불쾌지수     77
좋음        0
dtype: int64
온도       32
습도       68
강수량     220
불쾌지수     77
dtype: int64


In [60]:
sr = sr.drop("불쾌지수")
print(sr)

온도      32
습도      68
강수량    220
좋음       0
dtype: int64


In [64]:
data = [19, 14, 12]
index = ['하나', '둘', '셋']
s = pd.Series(data, index)
print(s)

s['둘'] = 22   # 인덱스로 접근해서 값 바꿈
print(s)
s.loc['하나'] = 1
print(s)

하나    19
둘     14
셋     12
dtype: int64
하나    19
둘     22
셋     12
dtype: int64
하나     1
둘     22
셋     12
dtype: int64


In [66]:
from pandas import Series

s = Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64


In [68]:
h = Series([10, 20, 30, 40, 50])
l = Series([1, 2, 3, 4, 5])

diff = (h - l)
print(diff)

0     9
1    18
2    27
3    36
4    45
dtype: int64


In [69]:
cond = diff > 30
print(cond)

0    False
1    False
2    False
3     True
4     True
dtype: bool


In [98]:
# 고가와 저가의 차이가 100 이상인 고가를 출력하시오

저가 = pd.Series([10, 200, 200, 400, 600])
고가 = pd.Series([100, 300, 400, 500, 600])

cond = (고가-저가 >= 100)
print(cond)

고가[cond]

0    False
1     True
2     True
3     True
4    False
dtype: bool


1    300
2    400
3    500
dtype: int64

In [121]:
# 종가가 80000원 이상 90000원 미만의 요일을 출력

data = [80010, 87100, 77800, 99000, 799000]
요일 = ['월', '화', '수', '목', '금']

종가 = pd.Series(data, 요일)
print(종가)

조건 = (종가 >= 80000) & (종가<90000)  # 파이썬에선 and를 사용하는데 여기선 and가 안되넹,, 
print(종가[조건].index)

월     80010
화     87100
수     77800
목     99000
금    799000
dtype: int64
Index(['월', '화'], dtype='object')


In [126]:
import numpy as np

x = np.arange(4).reshape(2, 2)
print(x)
y = np.arange(3, -1, -1).reshape(2, 2)  # 왜(3, -1, -1)이냐면 0을 입력하면 0은 포함 안되서
print(y)

s1 = np.matmul(x, y)  # x랑 y 곱하기
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[1 0]
 [9 4]]


In [131]:
x = np.arange(4).reshape(2, 2)
print(x)

s1 = np.abs(x)  # 절대값 
print(s1)

s2 = np.square(x)  # 2제곱
print(s2)

s3 = np.sqrt(x)  # 루트
print(s3)

s4 = np.log(x)  # 로그값
print(s4)

[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[0.         1.        ]
 [1.41421356 1.73205081]]
[[      -inf 0.        ]
 [0.69314718 1.09861229]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log
  del sys.path[0]


In [132]:
x = np.arange(4).reshape(2, 2)
print(x)
y = np.arange(3, -1, -1).reshape(2, 2)
print(y)

s1 = np.where(x>y, x, y)
print(s1)

[[0 1]
 [2 3]]
[[3 2]
 [1 0]]
[[3 2]
 [2 3]]


In [136]:
import pandas as pd

values = [[32, 68, 220, 72], 
         [20, 30, 0, 12],
         [38, 81, 0, 91]]

df = pd.DataFrame(values)
print(df)
print(df[0][1])  # list 의 행과 열이 바뀜 

list = [[32, 68, 220, 72], 
         [20, 30, 0, 12],
         [38, 81, 0, 91]]
print(list[0][1])

    0   1    2   3
0  32  68  220  72
1  20  30    0  12
2  38  81    0  91
20
68


In [168]:
import pandas as pd

values = [[32, 68, 220, 72], 
         [20, 30, 0, 12],
         [38, 81, 0, 91]]

columns = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름' ]

df = pd.DataFrame(values, index, columns)
print(df)
print()
print(df['온도'])
print(df['온도']['늦봄'])
print(df.loc[['늦봄']])  # loc: index, Seires 리턴 
print()
print(df.iloc[1]) # iloc: 행번호 리턴 
# df [ '칼럼이름' ] 하나의 열만 인덱싱
# df [ [ '칼럼이름' ] ] 하나의 열만 인덱싱 하는데 데이터프레임모양으로 출력
# df [ [ '칼럼이름1', '칼럼이름2' ] ] 여러개의 열은 리스트로 인덱싱

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91

초여름    32
늦봄     20
한여름    38
Name: 온도, dtype: int64
20
    온도  습도  강수량  불쾌지수
늦봄  20  30    0    12

온도      20
습도      30
강수량      0
불쾌지수    12
Name: 늦봄, dtype: int64


In [163]:
import pandas as pd

values = [[32, 68, 220, 72], 
         [20, 30, 0, 12],
         [38, 81, 0, 91]]

columns = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름' ]

df = pd.DataFrame(values, index, columns)

print(df)
print(df.index)
print(df.columns)
print(df.values)
df[['온도', '강수량']]

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91
Index(['초여름', '늦봄', '한여름'], dtype='object')
Index(['온도', '습도', '강수량', '불쾌지수'], dtype='object')
[[ 32  68 220  72]
 [ 20  30   0  12]
 [ 38  81   0  91]]


온도  강수량
초여름  32  220
늦봄   20    0
한여름  38    0

In [172]:
df.iloc[[0, 1]]
df.loc[['초여름', '늦봄']]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [173]:
df.iloc[0:2]

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [174]:
df.loc['초여름':'늦봄']

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12

In [175]:
import pandas as pd

values = [[32, 68, 220, 72], 
         [20, 30, 0, 12],
         [38, 81, 0, 91]]

columns = ['온도', '습도', '강수량', '불쾌지수']
index = ['초여름', '늦봄', '한여름' ]

df = pd.DataFrame(values, index, columns)

df

온도  습도  강수량  불쾌지수
초여름  32  68  220    72
늦봄   20  30    0    12
한여름  38  81    0    91

In [180]:
print(df.loc['초여름', '온도'])  # 인덱스: 행 x 열
print(df.loc[:, '온도'])  # 전체 행 x 온도 열 
print(df.loc[:, '습도':'강수량'])  # 행번호(인덱스로) 접근하기 때문에 강수량이 출력됨

32
초여름    32
늦봄     20
한여름    38
Name: 온도, dtype: int64
     습도  강수량
초여름  68  220
늦봄   30    0
한여름  81    0


In [186]:
# 온도가 30 이상인 모든 행 출력
import pandas as pd

values = [[32, 68, 220, 72], 
         [20, 30, 0, 12],
         [38, 81, 0, 91]]
columns = ['온도', '습도', '강수량', '불쾌지수']   # 열
index = ['초여름', '늦봄', '한여름' ]   # 행
df = pd.DataFrame(values, index, columns)

cond = df['온도']>=30
print(df[cond])
# df['초여름'] 대괄호를 사용할 경우 행은 못오고 열만 올 수 있다 그래서 이건 오류남
# 만약 행을 사용하고 싶다면 

     온도  습도  강수량  불쾌지수
초여름  32  68  220    72
한여름  38  81    0    91


KeyError: '초여름'